### ISSUE TITLE
Optimeister is not keeping the parameters

### ISSUE THREAD

**Issue by alitan** [dylanroscover/TDComponents#1]
Hi, 
I love the idea of Optimeister. But it is really useless for me. When i create a .tox file with several Optimeisters in it, it keeps the operation type but not the other settings. It puts everything to default. Is that a bug or a limitation?

Thanks.

**Comment by dylanroscover** [comment]
This is a bug; looking into it.  Thanks for the report.

**Comment by dylanroscover** [comment]
Hi @alitan this is fixed in version 0.6.52 of Optimeister, which I just pushed.

**Comment by alitan** [comment]
Oh awesome!!! Thank you so much.
_A
